const countries: Country[] = [
  { name: "Afghanistan", iso: "af" },
  { name: "Albania", iso: "al" },
  { name: "Algeria", iso: "dz" },
  { name: "Andorra", iso: "ad" },
  { name: "Angola", iso: "ao" },
  { name: "Antigua and Barbuda", iso: "ag" },
  { name: "Argentina", iso: "ar" },
  { name: "Armenia", iso: "am" },
  { name: "Australia", iso: "au" },
  { name: "Austria", iso: "at" },
  { name: "Azerbaijan", iso: "az" },
  { name: "Bahrain", iso: "bh" },
  { name: "Bangladesh", iso: "bd" },
  { name: "Barbados", iso: "bb" },
  { name: "Belarus", iso: "by" },
  { name: "Belgium", iso: "be" },
  { name: "Belize", iso: "bz" },
  { name: "Benin", iso: "bj" },
  { name: "Bhutan", iso: "bt" },
  { name: "Bolivia", iso: "bo" },
  { name: "Bosnia and Herzegovina", iso: "ba" },
  { name: "Botswana", iso: "bw" },
  { name: "Brazil", iso: "br" },
  { name: "Brunei", iso: "bn" },
  { name: "Bulgaria", iso: "bg" },
  { name: "Burkina Faso", iso: "bf" },
  { name: "Burundi", iso: "bi" },
  { name: "Cape Verde", iso: "cv" },
  { name: "Cambodia", iso: "kh" },
  { name: "Cameroon", iso: "cm" },
  { name: "Canada", iso: "ca" },
  { name: "Central African Republic", iso: "cf" },
  { name: "Chad", iso: "td" },
  { name: "Chile", iso: "cl" },
  { name: "China", iso: "cn" },
  { name: "Colombia", iso: "co" },
  { name: "Comoros", iso: "km" },
  { name: "Costa Rica", iso: "cr" },
  { name: "Croatia", iso: "hr" },
  { name: "Cuba", iso: "cu" },
  { name: "Cyprus", iso: "cy" },
  { name: "Czechia", iso: "cz" },
  { name: "Democratic Republic of the Congo", iso: "cd" },
  { name: "Denmark", iso: "dk" },
  { name: "Djibouti", iso: "dj" },
  { name: "Dominica", iso: "dm" },
  { name: "Dominican Republic", iso: "do" },
  { name: "Ecuador", iso: "ec" },
  { name: "Egypt", iso: "eg" },
  { name: "El Salvador", iso: "sv" },
  { name: "Equatorial Guinea", iso: "gq" },
  { name: "Eritrea", iso: "er" },
  { name: "Estonia", iso: "ee" },
  { name: "Eswatini", iso: "sz" },
  { name: "Ethiopia", iso: "et" },
  { name: "Fiji", iso: "fj" },
  { name: "Finland", iso: "fi" },
  { name: "France", iso: "fr" },
  { name: "Gabon", iso: "ga" },
  { name: "Georgia", iso: "ge" },
  { name: "Germany", iso: "de" },
  { name: "Ghana", iso: "gh" },
  { name: "Greece", iso: "gr" },
  { name: "Grenada", iso: "gd" },
  { name: "Guatemala", iso: "gt" },
  { name: "Guinea", iso: "gn" },
  { name: "Guinea-Bissau", iso: "gw" },
  { name: "Guyana", iso: "gy" },
  { name: "Haiti", iso: "ht" },
  { name: "Honduras", iso: "hn" },
  { name: "Hungary", iso: "hu" },
  { name: "Iceland", iso: "is" },
  { name: "India", iso: "in" },
  { name: "Indonesia", iso: "id" },
  { name: "Iran", iso: "ir" },
  { name: "Iraq", iso: "iq" },
  { name: "Ireland", iso: "ie" },
  { name: "Israel", iso: "il" },
  { name: "Italy", iso: "it" },
  { name: "Ivory Coast", iso: "ci" },
  { name: "Jamaica", iso: "jm" },
  { name: "Japan", iso: "jp" },
  { name: "Jordan", iso: "jo" },
  { name: "Kazakhstan", iso: "kz" },
  { name: "Kenya", iso: "ke" },
  { name: "Kiribati", iso: "ki" },
  { name: "Kosovo", iso: "xk" },
  { name: "Kuwait", iso: "kw" },
  { name: "Kyrgyzstan", iso: "kg" },
  { name: "Laos", iso: "la" },
  { name: "Latvia", iso: "lv" },
  { name: "Lebanon", iso: "lb" },
  { name: "Lesotho", iso: "ls" },
  { name: "Liberia", iso: "lr" },
  { name: "Libya", iso: "ly" },
  { name: "Liechtenstein", iso: "li" },
  { name: "Lithuania", iso: "lt" },
  { name: "Luxembourg", iso: "lu" },
  { name: "Madagascar", iso: "mg" },
  { name: "Malawi", iso: "mw" },
  { name: "Malaysia", iso: "my" },
  { name: "Maldives", iso: "mv" },
  { name: "Mali", iso: "ml" },
  { name: "Malta", iso: "mt" },
  { name: "Marshall Islands", iso: "mh" },
  { name: "Mauritania", iso: "mr" },
  { name: "Mauritius", iso: "mu" },
  { name: "Mexico", iso: "mx" },
  { name: "Micronesia", iso: "fm" },
  { name: "Moldova", iso: "md" },
  { name: "Monaco", iso: "mc" },
  { name: "Mongolia", iso: "mn" },
  { name: "Montenegro", iso: "me" },
  { name: "Morocco", iso: "ma" },
  { name: "Mozambique", iso: "mz" },
  { name: "Myanmar", iso: "mm" },
  { name: "Namibia", iso: "na" },
  { name: "Nauru", iso: "nr" },
  { name: "Nepal", iso: "np" },
  { name: "Netherlands", iso: "nl" },
  { name: "New Zealand", iso: "nz" },
  { name: "Nicaragua", iso: "ni" },
  { name: "Niger", iso: "ne" },
  { name: "Nigeria", iso: "ng" },
  { name: "North Korea", iso: "kp" },
  { name: "North Macedonia", iso: "mk" },
  { name: "Norway", iso: "no" },
  { name: "Oman", iso: "om" },
  { name: "Pakistan", iso: "pk" },
  { name: "Palau", iso: "pw" },
  { name: "Palestine", iso: "ps" },
  { name: "Panama", iso: "pa" },
  { name: "Papua New Guinea", iso: "pg" },
  { name: "Paraguay", iso: "py" },
  { name: "Peru", iso: "pe" },
  { name: "Philippines", iso: "ph" },
  { name: "Poland", iso: "pl" },
  { name: "Portugal", iso: "pt" },
  { name: "Qatar", iso: "qa" },
  { name: "Republic of the Congo", iso: "cg" },
  { name: "Romania", iso: "ro" },
  { name: "Russia", iso: "ru" },
  { name: "Rwanda", iso: "rw" },
  { name: "Saint Kitts and Nevis", iso: "kn" },
  { name: "Saint Lucia", iso: "lc" },
  { name: "Saint Vincent and the Grenadines", iso: "vc" },
  { name: "Samoa", iso: "ws" },
  { name: "San Marino", iso: "sm" },
  { name: "Sao Tome and Principe", iso: "st" },
  { name: "Saudi Arabia", iso: "sa" },
  { name: "Senegal", iso: "sn" },
  { name: "Serbia", iso: "rs" },
  { name: "Seychelles", iso: "sc" },
  { name: "Sierra Leone", iso: "sl" },
  { name: "Singapore", iso: "sg" },
  { name: "Slovakia", iso: "sk" },
  { name: "Slovenia", iso: "si" },
  { name: "Solomon Islands", iso: "sb" },
  { name: "Somalia", iso: "so" },
  { name: "South Africa", iso: "za" },
  { name: "South Korea", iso: "kr" },
  { name: "South Sudan", iso: "ss" },
  { name: "Spain", iso: "es" },
  { name: "Sri Lanka", iso: "lk" },
  { name: "Sudan", iso: "sd" },
  { name: "Suriname", iso: "sr" },
  { name: "Sweden", iso: "se" },
  { name: "Switzerland", iso: "ch" },
  { name: "Syria", iso: "sy" },
  { name: "Taiwan", iso: "tw" },
  { name: "Tajikistan", iso: "tj" },
  { name: "Tanzania", iso: "tz" },
  { name: "Thailand", iso: "th" },
  { name: "The Bahamas", iso: "bs" },
  { name: "The Gambia", iso: "gm" },
  { name: "Timor-Leste", iso: "tl" },
  { name: "Togo", iso: "tg" },
  { name: "Tonga", iso: "to" },
  { name: "Trinidad and Tobago", iso: "tt" },
  { name: "Tunisia", iso: "tn" },
  { name: "Turkey", iso: "tr" },
  { name: "Turkmenistan", iso: "tm" },
  { name: "Tuvalu", iso: "tv" },
  { name: "Uganda", iso: "ug" },
  { name: "Ukraine", iso: "ua" },
  { name: "United Arab Emirates", iso: "ae" },
  { name: "United Kingdom", iso: "gb" },
  { name: "United States", iso: "us" },
  { name: "Uruguay", iso: "uy" },
  { name: "Uzbekistan", iso: "uz" },
  { name: "Vanuatu", iso: "vu" },
  { name: "Vatican City", iso: "va" },
  { name: "Venezuela", iso: "ve" },
  { name: "Vietnam", iso: "vn" },
  { name: "Yemen", iso: "ye" },
  { name: "Zambia", iso: "zm" },
  { name: "Zimbabwe", iso: "zw" },
];

export default countries;
